version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3031:3031"
    depends_on:
      - db
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
    volumes:
      - db_data:/var/lib/postgresql/data
  migrate:
    build:
      context: .
      target: migrate-runner
    command: "pnpm run migrate"
    depends_on:
      - db
      - web
  seed:
    build:
      context: .
      target: migrate-runner
    command: "pnpm run seed"
    depends_on:
      - db
      - web

volumes:
  db_data:
  redis_data:

# Run the following command to start the services:
# docker compose up, docker compose up -d (detached mode)

# stop the services:
# docker compose down

# --------------------------------------------

# For current development, I suggest just run the db into docker, and run the web server locally.
# To do that, you can run the following command:
# ``` docker compose up db -d ```

# maybe we dont need to run the migrate and seed services, the indication for development is just up redis and db
# and run the the server in turbo, to run front and backend

# ```
# ./apps/api -> docker-compose up redis db
#
# ./ -> pnpm run dev
# ```
